spring:
  application:
    name: umfrage-backend

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: ${server_port:8080}
  connection-timeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

---

spring:
  profiles: prod
  datasource:
    url: jdbc:mysql://umfragedb.cumnnbmhkrdn.eu-central-1.rds.amazonaws.com:3306/umfrage
    username: Notronic
    password: verysafepwd
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy