spring:
  application:
    name: umfrage-backend
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:database/online-umfrage.db
  jpa:
    database-platform: com.enigmabridge.hibernate.dialect.SQLiteDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: ${server_port:8080}
  connection-timeout: 10000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000
