server:
  port: ${server_port:8761}
  connection-timeout: 10000


eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
  connection-timeout: 10000